# Generated by Django 3.1.7 on 2022-02-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220225_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='OM',
            field=models.CharField(max_length=100, verbose_name='OM'),
        ),
    ]
